// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleauthenticator.proxies;

public class GoogleAuthCredential
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject googleAuthCredentialMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleAuthenticator.GoogleAuthCredential";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserName("UserName"),
		ga_SecretKey("ga_SecretKey"),
		url("url"),
		GoogleAuthCredential_User("GoogleAuthenticator.GoogleAuthCredential_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GoogleAuthCredential(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GoogleAuthenticator.GoogleAuthCredential"));
	}

	protected GoogleAuthCredential(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject googleAuthCredentialMendixObject)
	{
		if (googleAuthCredentialMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GoogleAuthenticator.GoogleAuthCredential", googleAuthCredentialMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GoogleAuthenticator.GoogleAuthCredential");

		this.googleAuthCredentialMendixObject = googleAuthCredentialMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GoogleAuthCredential.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googleauthenticator.proxies.GoogleAuthCredential initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googleauthenticator.proxies.GoogleAuthCredential.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static googleauthenticator.proxies.GoogleAuthCredential initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googleauthenticator.proxies.GoogleAuthCredential(context, mendixObject);
	}

	public static googleauthenticator.proxies.GoogleAuthCredential load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googleauthenticator.proxies.GoogleAuthCredential.initialize(context, mendixObject);
	}

	public static java.util.List<googleauthenticator.proxies.GoogleAuthCredential> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<googleauthenticator.proxies.GoogleAuthCredential> result = new java.util.ArrayList<googleauthenticator.proxies.GoogleAuthCredential>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//GoogleAuthenticator.GoogleAuthCredential" + xpathConstraint))
			result.add(googleauthenticator.proxies.GoogleAuthCredential.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of ga_SecretKey
	 */
	public final java.lang.String getga_SecretKey()
	{
		return getga_SecretKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ga_SecretKey
	 */
	public final java.lang.String getga_SecretKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ga_SecretKey.toString());
	}

	/**
	 * Set value of ga_SecretKey
	 * @param ga_secretkey
	 */
	public final void setga_SecretKey(java.lang.String ga_secretkey)
	{
		setga_SecretKey(getContext(), ga_secretkey);
	}

	/**
	 * Set value of ga_SecretKey
	 * @param context
	 * @param ga_secretkey
	 */
	public final void setga_SecretKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ga_secretkey)
	{
		getMendixObject().setValue(context, MemberNames.ga_SecretKey.toString(), ga_secretkey);
	}

	/**
	 * @return value of url
	 */
	public final java.lang.String geturl()
	{
		return geturl(getContext());
	}

	/**
	 * @param context
	 * @return value of url
	 */
	public final java.lang.String geturl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.url.toString());
	}

	/**
	 * Set value of url
	 * @param url
	 */
	public final void seturl(java.lang.String url)
	{
		seturl(getContext(), url);
	}

	/**
	 * Set value of url
	 * @param context
	 * @param url
	 */
	public final void seturl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.url.toString(), url);
	}

	/**
	 * @return value of GoogleAuthCredential_User
	 */
	public final system.proxies.User getGoogleAuthCredential_User() throws com.mendix.core.CoreException
	{
		return getGoogleAuthCredential_User(getContext());
	}

	/**
	 * @param context
	 * @return value of GoogleAuthCredential_User
	 */
	public final system.proxies.User getGoogleAuthCredential_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GoogleAuthCredential_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GoogleAuthCredential_User
	 * @param googleauthcredential_user
	 */
	public final void setGoogleAuthCredential_User(system.proxies.User googleauthcredential_user)
	{
		setGoogleAuthCredential_User(getContext(), googleauthcredential_user);
	}

	/**
	 * Set value of GoogleAuthCredential_User
	 * @param context
	 * @param googleauthcredential_user
	 */
	public final void setGoogleAuthCredential_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User googleauthcredential_user)
	{
		if (googleauthcredential_user == null)
			getMendixObject().setValue(context, MemberNames.GoogleAuthCredential_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GoogleAuthCredential_User.toString(), googleauthcredential_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return googleAuthCredentialMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googleauthenticator.proxies.GoogleAuthCredential that = (googleauthenticator.proxies.GoogleAuthCredential) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GoogleAuthenticator.GoogleAuthCredential";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
