// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleauthenticator.proxies;

public class QRValidation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject qRValidationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleAuthenticator.QRValidation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PIN("PIN"),
		QRValidation_GoogleAuthCredential("GoogleAuthenticator.QRValidation_GoogleAuthCredential");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public QRValidation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GoogleAuthenticator.QRValidation"));
	}

	protected QRValidation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject qRValidationMendixObject)
	{
		if (qRValidationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GoogleAuthenticator.QRValidation", qRValidationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GoogleAuthenticator.QRValidation");

		this.qRValidationMendixObject = qRValidationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'QRValidation.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static googleauthenticator.proxies.QRValidation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googleauthenticator.proxies.QRValidation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static googleauthenticator.proxies.QRValidation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googleauthenticator.proxies.QRValidation(context, mendixObject);
	}

	public static googleauthenticator.proxies.QRValidation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googleauthenticator.proxies.QRValidation.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PIN
	 */
	public final java.lang.String getPIN()
	{
		return getPIN(getContext());
	}

	/**
	 * @param context
	 * @return value of PIN
	 */
	public final java.lang.String getPIN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PIN.toString());
	}

	/**
	 * Set value of PIN
	 * @param pin
	 */
	public final void setPIN(java.lang.String pin)
	{
		setPIN(getContext(), pin);
	}

	/**
	 * Set value of PIN
	 * @param context
	 * @param pin
	 */
	public final void setPIN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pin)
	{
		getMendixObject().setValue(context, MemberNames.PIN.toString(), pin);
	}

	/**
	 * @return value of QRValidation_GoogleAuthCredential
	 */
	public final googleauthenticator.proxies.GoogleAuthCredential getQRValidation_GoogleAuthCredential() throws com.mendix.core.CoreException
	{
		return getQRValidation_GoogleAuthCredential(getContext());
	}

	/**
	 * @param context
	 * @return value of QRValidation_GoogleAuthCredential
	 */
	public final googleauthenticator.proxies.GoogleAuthCredential getQRValidation_GoogleAuthCredential(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googleauthenticator.proxies.GoogleAuthCredential result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QRValidation_GoogleAuthCredential.toString());
		if (identifier != null)
			result = googleauthenticator.proxies.GoogleAuthCredential.load(context, identifier);
		return result;
	}

	/**
	 * Set value of QRValidation_GoogleAuthCredential
	 * @param qrvalidation_googleauthcredential
	 */
	public final void setQRValidation_GoogleAuthCredential(googleauthenticator.proxies.GoogleAuthCredential qrvalidation_googleauthcredential)
	{
		setQRValidation_GoogleAuthCredential(getContext(), qrvalidation_googleauthcredential);
	}

	/**
	 * Set value of QRValidation_GoogleAuthCredential
	 * @param context
	 * @param qrvalidation_googleauthcredential
	 */
	public final void setQRValidation_GoogleAuthCredential(com.mendix.systemwideinterfaces.core.IContext context, googleauthenticator.proxies.GoogleAuthCredential qrvalidation_googleauthcredential)
	{
		if (qrvalidation_googleauthcredential == null)
			getMendixObject().setValue(context, MemberNames.QRValidation_GoogleAuthCredential.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.QRValidation_GoogleAuthCredential.toString(), qrvalidation_googleauthcredential.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return qRValidationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googleauthenticator.proxies.QRValidation that = (googleauthenticator.proxies.QRValidation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GoogleAuthenticator.QRValidation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
