// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package googleauthenticator.actions;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class LogAttemptKillSessionThrowException extends CustomJavaAction<java.lang.Void>
{
	public LogAttemptKillSessionThrowException(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.getLogger("GoogleAuth").error("USER: [" + this.getContext().getSession().getUserName() + "] IS ATTEMPTING TO SKIP THE TWO-FACTOR, WE ARE NOT IN DEV MODE. (Session: " + this.getContext().getSession().getId().toString() + ")");

		Core.logout(this.getContext().getSession());
		throw new CoreException("USER: [" + this.getContext().getSession().getUserName() + "] IS ATTEMPTING TO SKIP THE TWO-FACTOR, WE ARE NOT IN DEV MODE. (Session: " + this.getContext().getSession().getId().toString() + ")");

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "LogAttemptKillSessionThrowException";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
