// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googleauthenticator.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the GoogleAuthenticator module
	public static void _AddGAuthToUser(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		Core.microflowCall("GoogleAuthenticator._AddGAuthToUser").withParams(params).execute(context);
	}
	public static boolean afterStartup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("GoogleAuthenticator.AfterStartup").withParams(params).execute(context);
	}
	public static googleauthenticator.proxies.GoogleAuthCredential createGoogleAuthCredentials(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleAuthenticator.CreateGoogleAuthCredentials").withParams(params).execute(context);
		return result == null ? null : googleauthenticator.proxies.GoogleAuthCredential.initialize(context, result);
	}
	public static java.util.List<administration.proxies.Account> dS_GetUsersWithGAuth(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("GoogleAuthenticator.DS_GetUsersWithGAuth").withParams(params).execute(context);
		java.util.List<administration.proxies.Account> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(administration.proxies.Account.initialize(context, obj));
		}
		return result;
	}
	public static googleauthenticator.proxies.QRValidation dS_GetValidationEntity(IContext context, googleauthenticator.proxies.GoogleAuthCredential _googleAuthCredential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleAuthCredential", _googleAuthCredential == null ? null : _googleAuthCredential.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleAuthenticator.DS_GetValidationEntity").withParams(params).execute(context);
		return result == null ? null : googleauthenticator.proxies.QRValidation.initialize(context, result);
	}
	public static googleauthenticator.proxies.GoogleAuthCredential findCreateGAuthCredentialForUser(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("GoogleAuthenticator.FindCreateGAuthCredentialForUser").withParams(params).execute(context);
		return result == null ? null : googleauthenticator.proxies.GoogleAuthCredential.initialize(context, result);
	}
	public static void login(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		Core.microflowCall("GoogleAuthenticator.Login").withParams(params).execute(context);
	}
	public static void mB_RemoveGoogleAuthForUser(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("GoogleAuthenticator.MB_RemoveGoogleAuthForUser").withParams(params).execute(context);
	}
	public static void nav_Homepage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("GoogleAuthenticator.Nav_Homepage").withParams(params).execute(context);
	}
	public static void updateRoles(IContext context, googleauthenticator.proxies.GoogleAuthCredential _googleAuthCredential, googleauthenticator.proxies.QRValidation _qRValidation)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GoogleAuthCredential", _googleAuthCredential == null ? null : _googleAuthCredential.getMendixObject());
		params.put("QRValidation", _qRValidation == null ? null : _qRValidation.getMendixObject());
		Core.microflowCall("GoogleAuthenticator.UpdateRoles").withParams(params).execute(context);
	}
	public static boolean validateAndConfirmNewLink(IContext context, googleauthenticator.proxies.QRValidation _qRValidation, googleauthenticator.proxies.GoogleAuthCredential _googleAuthCredential)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("QRValidation", _qRValidation == null ? null : _qRValidation.getMendixObject());
		params.put("GoogleAuthCredential", _googleAuthCredential == null ? null : _googleAuthCredential.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("GoogleAuthenticator.ValidateAndConfirmNewLink").withParams(params).execute(context);
	}
}